config:
  data_root: "/data2/datasets/drivelm/data/coda"
  batch_size: 1

# tasks = ['general_perception', 'region_perception', 'driving_suggestion']
# 

tasks:
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output2/internvl2-8b/original_test_gp_ft10/checkpoint-1737"
    json_path: "/data2/datasets/drivelm/data/qas/original/original_test_general_perception.jsonl"
    out_json_path: "/data2/datasets/drivelm/output2/nexusad/241018_epoch/test_gp_epoch_3.jsonl"
    gpu: 2
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output2/internvl2-8b/original_test_gp_ft10/checkpoint-3475"
    json_path: "/data2/datasets/drivelm/data/qas/original/original_test_general_perception.jsonl"
    out_json_path: "/data2/datasets/drivelm/output2/nexusad/241018_epoch/test_gp_epoch_6.jsonl"
    gpu: 3
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output2/internvl2-8b/original_test_gp_ft10/checkpoint-5213"
    json_path: "/data2/datasets/drivelm/data/qas/original/original_test_general_perception.jsonl"
    out_json_path: "/data2/datasets/drivelm/output2/nexusad/241018_epoch/test_gp_epoch_9.jsonl"
    gpu: 0
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output2/internvl2-8b/original_test_gp_ft10/checkpoint-6951"
    json_path: "/data2/datasets/drivelm/data/qas/original/original_test_general_perception.jsonl"
    out_json_path: "/data2/datasets/drivelm/output2/nexusad/241018_epoch/test_gp_epoch_12.jsonl"
    gpu: 2
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output2/internvl2-8b/original_test_gp_ft10/checkpoint-8688"
    json_path: "/data2/datasets/drivelm/data/qas/original/original_test_general_perception.jsonl"
    out_json_path: "/data2/datasets/drivelm/output2/nexusad/241018_epoch/test_gp_epoch_15.jsonl"
    gpu: 3


