config:
  data_root: "/data2/datasets/drivelm/data/coda"
  batch_size: 1

# tasks = ['general_perception', 'region_perception', 'driving_suggestion']
# 

tasks:
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output4/1112_gp_icl_ift/checkpoint-2316"
    json_path: "/data2/datasets/drivelm/similarity_rank/241110_rank_for_ft2/test_vt_gp_v1_2.jsonl"
    out_json_path: "/data2/datasets/drivelm/241113_icl_swift/test_icl_gp_v1_2_ft_4_his_0.jsonl"
    gpu: 1
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output4/1112_ds_icl_ift/checkpoint-2316"
    json_path: "/data2/datasets/drivelm/similarity_rank/241110_rank_for_ft2/test_vt_ds_v1_2.jsonl"
    out_json_path: "/data2/datasets/drivelm/241113_icl_swift/test_icl_ds_v1_2_ft_3_his_0.jsonl"
    gpu: 0




