config:
  data_root: "/data2/datasets/drivelm/data/coda"
  batch_size: 1

# tasks = ['general_perception', 'region_perception', 'driving_suggestion']
# 

tasks:
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output2/internvl2-8b/v1-20241023-225450_ori_ds/checkpoint-2316"
    json_path: "/data2/datasets/drivelm/data/qas/original/original_test_driving_suggestion.jsonl"
    out_json_path: "/data2/datasets/drivelm/output2/nexusad/241027_structure/ori_vl_8b_test_ds_ft_4.jsonl"
    gpu: 2
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output2/internvl2-8b/v3-20241024-023750_structure_gp/checkpoint-2316"
    json_path: "/data2/datasets/drivelm/data/qas/structure/structure_test_general_perception.jsonl"
    out_json_path: "/data2/datasets/drivelm/output2/nexusad/241027_structure/struct_vl_8b_test_gp_ft_4.jsonl"
    gpu: 3
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output2/internvl2-8b/v5-20241024-024519_structure_ds/checkpoint-2316"
    json_path: "/data2/datasets/drivelm/data/qas/structure/structure_test_driving_suggestion.jsonl"
    out_json_path: "/data2/datasets/drivelm/output2/nexusad/241027_structure/struct_vl_8b_test_ds_ft_4.jsonl"
    gpu: 2


