config:
  data_root: "/data2/datasets/drivelm/data/coda"
  batch_size: 1

# tasks = ['general_perception', 'region_perception', 'driving_suggestion']
# 

tasks:
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output2/internvl2-8b/v3-20241024-023750_structure_gp/checkpoint-2316"
    json_path: "/data1/nemo/projects/aaaa_new/aaaa_0816/final_prompt/test_gp_v5d2.jsonl"
    out_json_path: "/data2/datasets/drivelm/output2/nexusad/241027_5d2/5d2_test_gp_run.jsonl"
    gpu: 2
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output2/internvl2-8b/v5-20241024-024519_structure_ds/checkpoint-2316"
    json_path: "/data1/nemo/projects/spatial_ad/检索生成/gen0814/test_ds_v9_top2.jsonl"
    out_json_path: "/data2/datasets/drivelm/output2/nexusad/241027_5d2/59_test_ds_run.jsonl"
    gpu: 3


