config:
  data_root: "/data2/datasets/drivelm/data/coda"
  batch_size: 1

# tasks = ['general_perception', 'region_perception', 'driving_suggestion']
# 

tasks:
  - model_dir: "/data1/nemo/projects/pre_weights/DeepSeek-VL-7B"
    ckpt_dir: ""
    json_path: "/data2/datasets/drivelm/data/qas/original/original_test_region_perception.jsonl"
    out_json_path: "/data2/datasets/drivelm/output2/nexusad/241025_ori_temp/ori_deepseek_test_rp_ft_4.jsonl"
    gpu: 0
  # - model_dir: ""
  #   ckpt_dir: "/data2/datasets/drivelm/output2/internvl2-8b/original_test_rp_ft_4/checkpoint-5100"
  #   json_path: "/data2/datasets/drivelm/data/qas/structure/structure_test_region_perception.jsonl"
  #   out_json_path: "/data2/datasets/drivelm/output2/nexusad/241025_ori_temp/struct_vl_8b_test_rp_ft_4.jsonl"
  #   gpu: 3


