config:
  data_root: "/data2/datasets/drivelm/data/coda"
  batch_size: 1

tasks:
  - model_dir: '/data1/nemo/projects/pre_weights/InternVL2-8B'
    ckpt_dir: ""
    json_path: "/data2/datasets/drivelm/data/qas/original/original_test_driving_suggestion.jsonl"
    out_json_path: "/data2/datasets/drivelm/output2/nexusad/241024_ori_vl_8b/ori_vl_8b_test_driving_suggestion.jsonl"
    gpu: 1
  - model_dir: '/data1/nemo/projects/pre_weights/InternVL2-8B'
    ckpt_dir: ""
    json_path: "/data2/datasets/drivelm/data/qas/original/original_test_region_perception.jsonl"
    out_json_path: "/data2/datasets/drivelm/output2/nexusad/241024_ori_vl_8b/ori_vl_8b_test_region_perception.jsonl"
    gpu: 1
  - model_dir: '/data1/nemo/projects/pre_weights/InternVL2-8B'
    ckpt_dir: ""
    json_path: "/data2/datasets/drivelm/data/qas/original/original_test_driving_suggestion.jsonl"
    out_json_path: "/data2/datasets/drivelm/output2/nexusad/241024_ori_vl_8b/ori_vl_8b_test_driving_suggestion.jsonl"
    gpu: 1


