config:
  data_root: "/data2/datasets/drivelm/data/coda"
  batch_size: 1

# tasks:
# {% for i, ckpt in enumerate(range(920, 18401, 920), start=1) %}
#   - model_dir: ""
#     ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-{{ ckpt }}"
#     json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
#     out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_{{ i }}.json"
#     gpu: [1,2]
# {% endfor %}

tasks:
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v11-20241117-140830/checkpoint-920"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test3/test_pred_26b_1.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v11-20241117-140830/checkpoint-1840"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test3/test_pred_26b_2.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v11-20241117-140830/checkpoint-2760"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test3/test_pred_26b_3.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v11-20241117-140830/checkpoint-3680"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test3/test_pred_26b_4.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v11-20241117-140830/checkpoint-4600"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test3/test_pred_26b_5.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v11-20241117-140830/checkpoint-5520"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test3/test_pred_26b_6.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v11-20241117-140830/checkpoint-6440"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test3/test_pred_26b_7.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v11-20241117-140830/checkpoint-7360"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test3/test_pred_26b_8.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v11-20241117-140830/checkpoint-8280"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test3/test_pred_26b_9.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v11-20241117-140830/checkpoint-9200"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test3/test_pred_26b_10.json"
    gpu: [1,2]

  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-920"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_1.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-1840"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_2.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-2760"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_3.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-3680"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_4.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-4600"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_5.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-5520"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_6.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-6440"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_7.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-7360"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_8.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-8280"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_9.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-9200"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_10.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-10120"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_11.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-11040"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_12.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-11960"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_13.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-12880"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_14.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-13800"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_15.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-14720"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_16.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-15640"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_17.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-16560"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_18.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-17480"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_19.json"
    gpu: [1,2]
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output/internvl2-26b/v12-20241118-202422/checkpoint-18400"
    json_path: "/data1/nemo/projects/241009_DriveLM/drivelm_data_demo/test_swift2.jsonl"
    out_json_path: "/data1/nemo/projects/241009_DriveLM/241121_test2/test_pred_26b_20.json"
    gpu: [1,2]




