config:
  data_root: "/data2/datasets/drivelm/data/coda"
  batch_size: 1

# tasks = ['general_perception', 'region_perception', 'driving_suggestion']
# 

tasks:
  # - model_dir: ""
  #   ckpt_dir: "/data2/datasets/drivelm/output2/internvl2-8b/v5-20241024-024519_structure_ds/checkpoint-1737"
  #   json_path: "/data2/datasets/drivelm/data/qas/new/new_test_driving_suggestion.jsonl"
  #   out_json_path: "/data2/datasets/drivelm/output2/nexusad/241025_ori_temp/ori_vl_8b_test_ds_ft_3.jsonl"
  #   gpu: 0
  # - model_dir: ""
  #   ckpt_dir: "/data2/datasets/drivelm/output2/internvl2-8b/v3-20241024-023750_structure_gp/checkpoint-1737"
  #   json_path: "/data2/datasets/drivelm/data/qas/new/new_test_general_perception.jsonl"
  #   out_json_path: "/data2/datasets/drivelm/output2/nexusad/241025_ori_temp/ori_vl_8b_test_gp_ft_3.jsonl"
  #   gpu: 1
  # - model_dir: ""
  #   ckpt_dir: "/data2/datasets/drivelm/output3/241103_gp_icl_text/checkpoint-1158"
  #   json_path: "/data2/datasets/drivelm/similarity_rank/bert/for_ft/test_vt_gp_top_no_img.jsonl"
  #   out_json_path: "/data2/datasets/drivelm/241105/new_vl_8b_text_gp_ft_2.jsonl"
  #   gpu: 2
  # - model_dir: ""
  #   ckpt_dir: "/data2/datasets/drivelm/output3/241103_gp_icl_text/checkpoint-579"
  #   json_path: "/data2/datasets/drivelm/similarity_rank/bert/for_ft/test_vt_gp_top_no_img.jsonl"
  #   out_json_path: "/data2/datasets/drivelm/241105/new_vl_8b_text_gp_ft_1.jsonl"
  #   gpu: 3
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output3/241103_gp_icl_text/checkpoint-1737"
    json_path: "/data2/datasets/drivelm/similarity_rank/bert/for_ft/test_vt_gp_top_no_img.jsonl"
    out_json_path: "/data2/datasets/drivelm/241105/new_vl_8b_text_gp_ft_3.jsonl"
    gpu: 2
  - model_dir: ""
    ckpt_dir: "/data2/datasets/drivelm/output3/241103_gp_icl_text/checkpoint-2316"
    json_path: "/data2/datasets/drivelm/similarity_rank/bert/for_ft/test_vt_gp_top_no_img.jsonl"
    out_json_path: "/data2/datasets/drivelm/241105/new_vl_8b_text_gp_ft_4.jsonl"
    gpu: 3




